### ISSUE TITLE
laminograhy tilt angle adapted angle2vecLami  function

### ISSUE THREAD

**Issue by hws203** [ShanghaiTech-IMPACT/Geometry-Aware-Attenuation-Learning-for-Sparse-View-CBCT-Reconstruction#2]
@Zhentao-Liu Below is my modified conebeam for angle2vecLami  function. Could you check my laminography case function is correct with input laminographyAngle(radian) param?

###############################################################
def angle2vecLami(angle, isocenter, sid, sad, proj_spacing_x, proj_spacing_y, laminographyAngle,type):
    # input: angle in rad
    # output: vec [12]
    cam_x = isocenter[0] + sad * np.cos(angle)
    cam_y = isocenter[1] + sad * np.sin(angle)
    cam_z = isocenter[2] + sad * np.tan(laminographyAngle)
    cam = np.array([cam_x, cam_y, cam_z])

    det_x = isocenter[0] - (sid-sad) * np.cos(angle)
    det_y = isocenter[1] - (sid-sad) * np.sin(angle)
    det_z = isocenter[2] - (sid-sad) * np.tan(laminographyAngle)
    det = np.array([det_x, det_y, det_z])

    u_x = proj_spacing_x * np.sin(angle)
    u_y = proj_spacing_y * np.cos(angle)

    u_vector = np.array([-u_x, u_y, 0])
    v_vector = np.array([0, 0, -proj_spacing_y])  # opposite direction for display purpose, not necessary

    if type == 'cone_vec':
        vec = np.concatenate([cam, det, u_vector, v_vector])
    elif type == 'parallel3d_vec':
        ray_dir = det - cam
        ray_dir = ray_dir / np.linalg.norm(ray_dir)
        vec = np.concatenate([ray_dir, det, u_vector, v_vector])
    return vec

**Comment by Zhentao-Liu** [comment]
Thanks for your interest in our work. Its my first time to hear about laminographyAngle. Could you provide more information, or some geometric figure about it. In the following, I provide more geometric description of my code. Hope these messages could help you.

The geometry of cbct scanning system is clearly shown in Fig. 2 of my paper. In fact, angle para represents "PrimaryAngle" which represents the rotational angle around z-axis (we assume z-axis align with patient plane). There is also another angle called "SecondaryAngle" which represents the rotational angle around y-axis. In fact, you can regard it as pitch angle which is widely applied in computer graphics. In my setting, we assume it to be zeros. For more details about "PrimaryAngle" and "SecondaryAngle", you could refer to https://dicom.innolitics.com/ciods/x-ray-angiographic-image/xa-positioner/00181510.

However, in real-world scanning system, "SecondaryAngle" is usually not exactly zeros due to the motion of X-ray source or some specific settings. And I've implement the code considering "SecondaryAngle" in following.  You can simply verify it through DRR simulation. The code in this repo will also be updated. I dont know if "SecondaryAngle" is just what you want. Hope this could help you.

```
def angle2vec(PrimaryAngle, SecondaryAngle, isocenter, sid, sad, proj_spacing_x, proj_spacing_y, type='cone_vec'):
    # input: PrimaryAngle, SecondaryAngle in rad
    # output: vec [12]

    cam_x = isocenter[0] + sad * np.cos(SecondaryAngle) * np.cos(PrimaryAngle)
    cam_y = isocenter[1] + sad * np.cos(SecondaryAngle) * np.sin(PrimaryAngle)
    cam_z = isocenter[2] + sad * np.sin(SecondaryAngle)
    cam = np.array([cam_x, cam_y, cam_z])

    det_x = isocenter[0] - (sid-sad) * np.cos(SecondaryAngle) * np.cos(PrimaryAngle)
    det_y = isocenter[1] - (sid-sad) * np.cos(SecondaryAngle) * np.sin(PrimaryAngle)
    det_z = isocenter[2] - (sid-sad) * np.sin(SecondaryAngle)
    det = np.array([det_x, det_y, det_z])

    u_x = -proj_spacing_x * np.sin(PrimaryAngle)
    u_y = proj_spacing_x  * np.cos(PrimaryAngle)
    u_z = 0
    
    v_x = proj_spacing_y * np.sin(SecondaryAngle) * np.cos(PrimaryAngle)
    v_y = proj_spacing_y * np.sin(SecondaryAngle) * np.sin(PrimaryAngle)
    v_z = -proj_spacing_y * np.cos(SecondaryAngle)  # opposite direction for display purpose, not necessary

    u_vector = np.array([u_x, u_y, u_z])
    v_vector = np.array([v_x, v_y, v_z])

    if type == 'cone_vec':
        vec = np.concatenate([cam, det, u_vector, v_vector])
    elif type == 'parallel3d_vec':
        ray_dir = det - cam
        ray_dir = ray_dir / np.linalg.norm(ray_dir)
        vec = np.concatenate([ray_dir, det, u_vector, v_vector])

    return vec
```

**Comment by hws203** [comment]
Yes, your secondary angle is also necessary for real detector tilt issue which comes from h/w incorrect assembly issue.
But my laminography angle is a intent angle for thin sample case ct. you can get more information from below site.
https://iopscience.iop.org/article/10.1088/1361-6501/aafcae

I want to test your model with my laminography projection images and that's ct volume image.

**Comment by hws203** [comment]
I will close this issue, if there is any more comments, please add your comments here

**Comment by Zhentao-Liu** [comment]
Okay, I'll check you provided file later.

**Comment by Zhentao-Liu** [comment]
I've just quickly read the file you provided.
![1](https://github.com/user-attachments/assets/0bbad02a-5401-4160-86ba-1c0c9ac7adb3)
![2](https://github.com/user-attachments/assets/47341abb-c3b4-4458-b3de-966d56ac4d86)
![3](https://github.com/user-attachments/assets/b7168def-21d1-4f6e-9ab2-05ee8bc1af94)
Take oblique angle alpha=30degree for example, just need to set "SecondaryAngle" = 30degree, just think "SecondaryAngle"as pitch angle, The rotation axis is set as vertical. Note -30 degree also works for x-ray penetrability, but 30 degree is correct for X-ray path checking.  In this way, we could just translate laminograph to normal ct imaging.

**Comment by hws203** [comment]
Thanks for your nice explanation, I will use your secondary param for my own laminography data sample case.
